### ISSUE TITLE
ImportError undefined symbol: iJIT_NotifyEvent when MKL 2024.1 is installed

### ISSUE THREAD

**Issue by davidwhealey** [agentmorris/MegaDetector#127] opened 2024-05-05 20:30 UTC
When using `environment-detector.yml` to install the `cameratraps-detector` environment, importing pytorch from within that environment raises an `undefined symbol: iJIT_NotifyEvent` error.  Pytorch may fix this at some point, but in the meantime  pinning mkl to version <= 2024.0 works. 

Addressed in [this](https://github.com/pytorch/pytorch/issues/123097) issue.

**Comment by agentmorris** [comment] 2024-05-05 21:34
Good catch!  I was able to reproduce this issue (which I had missed because I had cached mkl versions on every machine I work on).  All the package versions in that environment file are pinned to minimize issues just like this, but one of those packages must be taking a dependency on an unpinned version of mkl.

I verified that forcing mkl=2024.0 in the environment file fixes this.  If you get a chance, please verify, but I'm sufficiently confident that I'm closing the issue.

This is going to come up for a zillion projects; MegaDetector is the least of PyTorch's concerns here. :)

Thanks for finding this!

**Closed by agentmorris** 2024-05-05 21:34 UTC
